# common variables across all roles

groupIdPath: "{{groupId | default('au/org/ala')}}"

ansible_python_interpreter: "auto"

docker_db_data_dir: "/data/dbs"

docker_web_image: "{{ docker_nginx_image | default('nginx:1.25') }}"

gatus_config_dir: "{{ data_dir }}/gatus/config"

# change auto to python for zoatrack
