---
- hosts: cas-servers
  vars:
    - cas_db_hostname: la_mysql
    - user_store_db_hostname: la_mysql
    - user_store_db_hostname: la_mysql
    - apikey_db_hostname: la_mysql
    - ticket_registry_db_hostname: la_mongodb
    - cas_audit_host: la_mongodb
    - cas_spring_session_host: la_mongodb
    - cas_tickets_host: la_mongodb
    - cas_tickets_host: la_mongodb
    - cas_services_host: la_mongodb
    - cas_services_host: la_mongodb
    - skip_handlers: true
    - cas_add_mongo_users: true
    - bootadmin_client_base_url: "https://{{ inventory_hostname}}/"
    - tomcat_user: "{{ docker_default_user }}"
    - nginx_user: "{{ docker_default_user }}"
    - cas_user: "{{ docker_default_user }}"
    - userdetails_user: "{{ docker_default_user }}"
    - apikey_user: "{{ docker_default_user }}"
    - cas_docker_host: la_cas
    - userdetails_docker_host: la_userdetails
    - cas_management_docker_host: la_cas-management
    - apikey_docker_host: la_apikey
  roles:
    - common
    - cas5
    - cas-management
    - userdetails
    - apikey
