---
- hosts: image-service
  vars:
    # deployment_type: swarm
    tomcat_user: "{{ docker_default_user }}"
    nginx_user: "{{ docker_default_user }}"
    image_user: "{{ docker_default_user }}"
    skip_handlers: true
  roles:
    - common
    - image-service
