---
- hosts: logger-service
  vars:
    # No deployment_type hardcoded!
    tomcat_user: "{{ docker_default_user }}"
    nginx_user: "{{ docker_default_user }}"
    skip_handlers: true
  roles:
    - common
    - logger-service
