---
- hosts: spatial
  vars:
    tomcat_user: "{{ docker_default_user }}"
    nginx_user: "{{ docker_default_user }}"
    skip_handlers: true
  roles:
    - common
    - spatial-service
    - spatial-hub
