- include_tasks: ../../common/tasks/setfacts.yml
  tags:
    - pipelines
    - docker
    - la-pipelines
    - hadoop_vocab
    - properties
    - la-pipelines-config

- name: create pipelines working directories
  file: path={{ item }} state=directory owner={{ spark_user }} group={{ spark_user }} recurse=true
  with_items:
    - "{{ data_dir }}/la-pipelines/config"
    - "{{ data_dir }}/spark-tmp"
    - "{{ data_dir }}/spark/conf"
    - "{{ data_dir }}/pipelines-shp"
    - "{{ data_dir }}/dwca-tmp"
    - "{{ data_dir }}/dwca-export"
    - "{{ data_dir }}/migration"
  tags:
    - properties
    - la-pipelines-config
    - pipelines
    - docker
    - la-pipelines

- name: create local pipelines data directories (container only)
  file: path={{ item }} state=directory owner={{ spark_user }} group={{ spark_user }} recurse=true
  with_items:
    - "{{ data_dir }}/la-pipelines/data"
    - "{{ data_dir }}/la-pipelines/data/all-datasets"
    - "{{ data_dir }}/la-pipelines/data/species"
    - "{{ data_dir }}/la-pipelines/data/jackknife"
    - "{{ data_dir }}/la-pipelines/data/clustering"
    - "{{ data_dir }}/la-pipelines/data/outlier"
    - "{{ data_dir }}/la-pipelines/vocabularies"
    - "{{ data_dir }}/la-pipelines/spark-tmp"
    - "{{ data_dir }}/la-pipelines/dwca-import"
    - "{{ data_dir }}/logs/pipelines"
  when: deployment_type == 'container'
  tags:
    - properties
    - la-pipelines-config
    - pipelines
    - docker
    - la-pipelines

- name: Update apt and install pipelines
  apt: update_cache=yes name=la-pipelines={{ pipelines_version }} force=yes
  when: deployment_type != 'container'
  tags:
    - pipelines
    - la-pipelines
    - la-pipelines-apt
    - apt

- name: Install pipelines config
  template:
    src: "{{ (deployment_type == 'container') | ternary('la-pipelines-docker.yaml.j2', 'la-pipelines-local.yaml') }}"
    dest: "{{ data_dir }}/la-pipelines/config/la-pipelines-local.yaml"
    mode: 0644
    output_encoding: iso-8859-1
  tags:
    - properties
    - la-pipelines-config
    - pipelines
    - la-pipelines

- name: Copy docker YAML files to {{ data_dir }}
  copy: src={{ item }} dest={{ data_dir }}/{{ item }}
  with_items:
    - ala-name-service.yml
    - ala-sensitive-data-service.yml
  tags:
    - pipelines
    - docker
    - properties


- name: Copy state/province vocab

  copy: src={{ item.src }} dest={{ data_dir }}/la-pipelines/config/{{ item.dest }} mode=0644
  with_items:
    - { src: "{{ state_province_centre_points_file }}", dest: stateProvinceCentrePoints.txt }
  when: state_province_centre_points_file is defined
  tags:
    - pipelines
    - hadoop
    - hadoop_vocab

- name: Download SHP files (includes global layer and EEZ derived from GBIFs geocode DB)
  get_url:
    url: "{{ pipelines_shapefiles_url | default('https://pipelines-shp.s3-ap-southeast-2.amazonaws.com/pipelines-shapefiles.zip') }}"
    dest: "{{ data_dir }}/pipelines-shp/pipelines-shapefiles.zip"
    checksum: "{{ pipelines_shapefiles_checksum | default('sha1:d4755425902e109e749c319f8d4ee98fa7ef2c4d') }}"
  tags:
    - pipelines
    - pipelines-layers

- name: Download SDS files with bitmaps
  get_url:
    url: "{{ sds_layers_with_bitmaps_url | default('https://archives.ala.org.au/archives/layers/sds-layers_with_bitmaps.tgz') }}"
    checksum: "{{ sds_layers_with_bitmaps_checksum | default('sha1:edc02525fdc1df0c587887b6df91d0b6ecd63cd7') }}"
    dest: "{{ data_dir }}/pipelines-shp/sds-layers.tgz"
  tags:
    - pipelines
    - pipelines-layers

- name: Download extra tar with layers
  get_url:
    url: "{{ pipelines_shapefiles_extra_url }}"
    checksum: "{{ pipelines_shapefiles_extra_checksum }}"
    dest: "{{ data_dir }}/pipelines-shp/extra-layers.tgz"
  tags:
    - pipelines
    - pipelines-layers
  when: pipelines_shapefiles_extra_url is defined

- name: Unpack SHP files
  unarchive:
    src: "{{ item }}"
    dest: "{{ data_dir }}/pipelines-shp"
    remote_src: yes
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
  with_items:
    - "{{ data_dir }}/pipelines-shp/pipelines-shapefiles.zip"
    - "{{ data_dir }}/pipelines-shp/sds-layers.tgz"
  tags:
    - pipelines
    - pipelines-layers

- name: Unpack SHP extra file
  unarchive:
    src: "{{ item }}"
    dest: "{{ data_dir }}/pipelines-shp"
    remote_src: yes
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
  with_items:
    - "{{ data_dir }}/pipelines-shp/extra-layers.tgz"
  tags:
    - pipelines
    - pipelines-layers
  when: pipelines_shapefiles_extra_url is defined

- name: Copy additional logging configs
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }}
  with_items:
    - { src: "{{ logback_pipelines_conf | default('logback.xml') }}", dest: "{{ data_dir }}/la-pipelines/config/logback.xml", owner: "{{ spark_user }}", group: "{{ spark_user }}" }
    - { src: "{{ log4j_spark_conf | default('log4j-spark.properties') }}", dest: "{{ data_dir }}/spark/conf/log4j.properties", owner: "{{ spark_user }}", group: "{{ spark_user }}" }
  tags:
    - pipelines
    - properties
    - la-pipelines-config
    - la-pipelines-logging-config
